### ISSUE TITLE
How to keep item selected in dropdownlist?

### ISSUE THREAD

**Issue by tanobi92** [nicolasbize/magicsuggest#225]
When I click select a item in dropdownlist, it will remove from dropdownlist. But I want to keep it in dropdownlist (not remove)?
Help me, please! Thank you very much!
<a href="http://imgur.com/8KnfuSP"><img src="http://i.imgur.com/8KnfuSP.png" title="source: imgur.com" /></a>

**Comment by nicolasbize** [comment]
use the allowDuplicates property

**Comment by tanobi92** [comment]
@nicolasbize ! Thank you for answering!
I have done. :)
